devices:
  # Earliest supported target.
  15:
    - armeabi
    - armeabi-v7a

  # Earlist supported target with a significant number of users.
  16:
    - armeabi
    - armeabi-v7a

  # Latest target.
  25:
    - armeabi
    - armeabi-v7a
    - arm64-v8a
    - x86
    - x86_64
